import screenSize from "./screenSize"
import colors from "./colors"
import sectionSizes from "./sectionSizes"

// Darken green and lighten pink

// Golden top: #d8ab4e

// Golden bottom: #b48c36

// Charcoal Black: #040404

///

// Dark Green: #164A41

// Medium Green: #4D774E

// Light Green: #9DC88D

// Natural Yellow: #F1B24A

// White: #FFFFFF

///

// Olive: #A3BCB6

// Green Leaf: #39603D

// Brown Grey: #3C403D

// Tanly: #DADED4

// White: #FFFFFF
// Champagne Pink: #F8DECD
///

const themeNanah7 = {
  baseTheme: {
    id: "baseTheme",
    backToTopButtonBackgroundColor: "#F8DECD",
    backToTopButtonFontColor: "#103730",
    headerBackgroundColor: "#F8DECD",
    headerFontColor: "#103730",
    // menuBackgroundColor: "#ff9f9fcf",
    menuFontColor: "#103730",
    heroBackgroundColor: "#F8DECD",
    heroFontColor: "#103730",
    mainBackgroundColor: "#F8DECD",
    mainFontColor: "#103730",
    footerBackgroundColor: "#F8DECD",
    footerFontColor: "#103730",
    modalBackdropBackgroundColor: "#F8DECD",
    modalBackdropFontColor: "#103730",
    modalOverlayBackgroundColor: "#F8DECD",
    modalOverlayFontColor: "#103730",
    toggleBackgroundColor: "#103730",
    toggleFontColor: "#103730",
    rightBackgroundColor: "#F8DECD",
    rightFontColor: "#103730",
    accentBackgroundColor: "#103730",
    accentFontColor: "#103730",
    socialMediaBackgroundColor: "#F8DECD",
    socialMediaFontColor: "#103730",
    buttonMediaBackgroundColor: "#F8DECD",
    buttonMediaFontColor: "#103730",
    landingPageBackgroundColor: "#103730",
    landingPageFontColor: "#F8DECD",
    contactPageBackgroundColor: "#F8DECD",
    contactPageFontColor: "#103730",
    salonPageBackgroundColor: "#F8DECD",
    salonPageFontColor: "#103730",
    loginPageBackgroundColor: "#F8DECD",
    loginPageFontColor: "#103730",
    signupPageBackgroundColor: "#F8DECD",
    signupPageFontColor: "#103730",
    stylistPageBackgroundColor: "#F8DECD",
    stylistPageFontColor: "#103730",
    bg: "#faeec8c9",
    color: "#91a681b8",
    secondaryColor: "#8fC1E3",
    tirtiaryColor: "#F7F9FB",
    backgroundColor: "linear-gradient(to right, #fadaddc4,#91a681)",
    modalBackgroundColor: "linear-gradient(to right, #894545c5,#384126d0)",
    screenSize,
    sectionSizes,
  },
  darkTheme: {
    id: "darkTheme",
    backToTopButtonBackgroundColor: "#103730",
    backToTopButtonFontColor: "#F8DECD",
    headerBackgroundColor: "#103730",
    headerFontColor: "#F8DECD",
    // menuBackgroundColor: "#103730",
    menuFontColor: "#F8DECD",
    heroBackgroundColor: "#103730",
    heroFontColor: "#F8DECD",
    mainBackgroundColor: "#103730",
    mainFontColor: "#F8DECD",
    footerBackgroundColor: "#103730",
    footerFontColor: "#F8DECD",
    modalBackdropBackgroundColor: "#103730",
    modalBackdropFontColor: "#F8DECD",
    modalOverlayBackgroundColor: "#103730",
    modalOverlayFontColor: "#F8DECD",
    toggleBackgroundColor: "#F8DECD",
    toggleFontColor: "#F8DECD",
    rightBackgroundColor: "#103730",
    rightFontColor: "#F8DECD",
    accentBackgroundColor: "#F8DECD",
    accentFontColor: "#F8DECD",
    socialMediaBackgroundColor: "#103730",
    socialMediaFontColor: "#F8DECD",
    buttonMediaBackgroundColor: "#103730",
    buttonMediaFontColor: "#F8DECD",
    landingPageBackgroundColor: "#F8DECD",
    landingPageFontColor: "#103730",
    contactPageBackgroundColor: "#103730",
    contactPageFontColor: "#F8DECD",
    salonPageBackgroundColor: "#103730",
    salonPageFontColor: "#F8DECD",
    loginPageBackgroundColor: "#103730",
    loginPageFontColor: "#F8DECD",
    signupPageBackgroundColor: "#103730",
    signupPageFontColor: "#F8DECD",
    stylistPageBackgroundColor: "#103730",
    stylistPageFontColor: "#F8DECD",
    bg: "#faeec8c9",
    color: "#91a681b8",
    secondaryColor: "#8fC1E3",
    tirtiaryColor: "#F7F9FB",
    backgroundColor: "linear-gradient(to right, #fadaddc4,#91a681)",
    modalBackgroundColor: "linear-gradient(to right, #894545c5,#384126d0)",
    screenSize,
    sectionSizes,
  },
}

const themeNanah6 = {
  baseTheme: {
    id: "baseTheme",
    backToTopButtonBackgroundColor: "#ffbebec4",
    backToTopButtonFontColor: "#103730",
    headerBackgroundColor: "#ffbebec4",
    headerFontColor: "#103730",
    // menuBackgroundColor: "#ff9f9fcf",
    menuFontColor: "#103730",
    heroBackgroundColor: "#ffbebec4",
    heroFontColor: "#103730",
    mainBackgroundColor: "#ffbebec4",
    mainFontColor: "#103730",
    footerBackgroundColor: "#ffbebec4",
    footerFontColor: "#103730",
    modalBackdropBackgroundColor: "#ffbebec4",
    modalBackdropFontColor: "#103730",
    modalOverlayBackgroundColor: "#ffbebec4",
    modalOverlayFontColor: "#103730",
    toggleBackgroundColor: "#103730",
    toggleFontColor: "#103730",
    rightBackgroundColor: "#ffbebec4",
    rightFontColor: "#103730",
    accentBackgroundColor: "#103730",
    accentFontColor: "#103730",
    socialMediaBackgroundColor: "#ffbebec4",
    socialMediaFontColor: "#103730",
    buttonMediaBackgroundColor: "#ffbebec4",
    buttonMediaFontColor: "#103730",
    landingPageBackgroundColor: "#103730",
    landingPageFontColor: "#ffbebec4",
    contactPageBackgroundColor: "#ffbebec4",
    contactPageFontColor: "#103730",
    salonPageBackgroundColor: "#ffbebec4",
    salonPageFontColor: "#103730",
    loginPageBackgroundColor: "#ffbebec4",
    loginPageFontColor: "#103730",
    signupPageBackgroundColor: "#ffbebec4",
    signupPageFontColor: "#103730",
    stylistPageBackgroundColor: "#ffbebec4",
    stylistPageFontColor: "#103730",
    bg: "#faeec8c9",
    color: "#91a681b8",
    secondaryColor: "#8fC1E3",
    tirtiaryColor: "#F7F9FB",
    backgroundColor: "linear-gradient(to right, #fadaddc4,#91a681)",
    modalBackgroundColor: "linear-gradient(to right, #894545c5,#384126d0)",
    screenSize,
    sectionSizes,
  },
  darkTheme: {
    id: "darkTheme",
    backToTopButtonBackgroundColor: "#103730",
    backToTopButtonFontColor: "#ffbebec4",
    headerBackgroundColor: "#103730",
    headerFontColor: "#ffbebec4",
    // menuBackgroundColor: "#103730",
    menuFontColor: "#ffbebec4",
    heroBackgroundColor: "#103730",
    heroFontColor: "#ffbebec4",
    mainBackgroundColor: "#103730",
    mainFontColor: "#ffbebec4",
    footerBackgroundColor: "#103730",
    footerFontColor: "#ffbebec4",
    modalBackdropBackgroundColor: "#103730",
    modalBackdropFontColor: "#ffbebec4",
    modalOverlayBackgroundColor: "#103730",
    modalOverlayFontColor: "#ffbebec4",
    toggleBackgroundColor: "#ffbebec4",
    toggleFontColor: "#ffbebec4",
    rightBackgroundColor: "#103730",
    rightFontColor: "#ffbebec4",
    accentBackgroundColor: "#ffbebec4",
    accentFontColor: "#ffbebec4",
    socialMediaBackgroundColor: "#103730",
    socialMediaFontColor: "#ffbebec4",
    buttonMediaBackgroundColor: "#103730",
    buttonMediaFontColor: "#ffbebec4",
    landingPageBackgroundColor: "#ffbebec4",
    landingPageFontColor: "#103730",
    contactPageBackgroundColor: "#103730",
    contactPageFontColor: "#ffbebec4",
    salonPageBackgroundColor: "#103730",
    salonPageFontColor: "#ffbebec4",
    loginPageBackgroundColor: "#103730",
    loginPageFontColor: "#ffbebec4",
    signupPageBackgroundColor: "#103730",
    signupPageFontColor: "#ffbebec4",
    stylistPageBackgroundColor: "#103730",
    stylistPageFontColor: "#ffbebec4",
    bg: "#faeec8c9",
    color: "#91a681b8",
    secondaryColor: "#8fC1E3",
    tirtiaryColor: "#F7F9FB",
    backgroundColor: "linear-gradient(to right, #fadaddc4,#91a681)",
    modalBackgroundColor: "linear-gradient(to right, #894545c5,#384126d0)",
    screenSize,
    sectionSizes,
  },
}

const themeNanah5 = {
  baseTheme: {
    id: "baseTheme",
    headerBackgroundColor: "#ffc2c2ed",
    headerFontColor: "#103730",
    menuBackgroundColor: "#ffc2c2ed",
    menuFontColor: "#103730",
    heroBackgroundColor: "#ffc2c2ed",
    heroFontColor: "#103730",
    mainBackgroundColor: "#ffc2c2ed",
    mainFontColor: "#103730",
    footerBackgroundColor: "#ffc2c2ed",
    footerFontColor: "#103730",
    modalBackdropBackgroundColor: "#ffc2c2ed",
    modalBackdropFontColor: "#103730",
    modalOverlayBackgroundColor: "#ffc2c2ed",
    modalOverlayFontColor: "#103730",
    toggleBackgroundColor: "#103730",
    toggleFontColor: "#103730",
    rightBackgroundColor: "#ffc2c2ed",
    rightFontColor: "#103730",
    accentBackgroundColor: "#103730",
    accentFontColor: "#103730",
    socialMediaBackgroundColor: "#ffc2c2ed",
    socialMediaFontColor: "#103730",
    buttonMediaBackgroundColor: "#ffc2c2ed",
    buttonMediaFontColor: "#103730",
    landingPageBackgroundColor: "#103730",
    landingPageFontColor: "#ffc2c2ed",
    contactPageBackgroundColor: "#ffc2c2ed",
    contactPageFontColor: "#103730",
    salonPageBackgroundColor: "#ffc2c2ed",
    salonPageFontColor: "#103730",
    signinPageBackgroundColor: "#ffc2c2ed",
    signinPageFontColor: "#103730",
    signupPageBackgroundColor: "#ffc2c2ed",
    signupPageFontColor: "#103730",
    stylistPageBackgroundColor: "#ffc2c2ed",
    stylistPageFontColor: "#103730",
    bg: "#faeec8c9",
    color: "#91a681b8",
    secondaryColor: "#8fC1E3",
    tirtiaryColor: "#F7F9FB",
    backgroundColor: "linear-gradient(to right, #fadaddc4,#91a681)",
    modalBackgroundColor: "linear-gradient(to right, #894545c5,#384126d0)",
    screenSize,
    sectionSizes,
  },
  darkTheme: {
    id: "darkTheme",
    headerBackgroundColor: "#103730",
    headerFontColor: "#ffc2c2ed",
    menuBackgroundColor: "#103730",
    menuFontColor: "#ffc2c2ed",
    heroBackgroundColor: "#103730",
    heroFontColor: "#ffc2c2ed",
    mainBackgroundColor: "#103730",
    mainFontColor: "#ffc2c2ed",
    footerBackgroundColor: "#103730",
    footerFontColor: "#ffc2c2ed",
    modalBackdropBackgroundColor: "#103730",
    modalBackdropFontColor: "#ffc2c2ed",
    modalOverlayBackgroundColor: "#103730",
    modalOverlayFontColor: "#ffc2c2ed",
    toggleBackgroundColor: "#ffc2c2ed",
    toggleFontColor: "#ffc2c2ed",
    rightBackgroundColor: "#103730",
    rightFontColor: "#ffc2c2ed",
    accentBackgroundColor: "#ffc2c2ed",
    accentFontColor: "#ffc2c2ed",
    socialMediaBackgroundColor: "#103730",
    socialMediaFontColor: "#ffc2c2ed",
    buttonMediaBackgroundColor: "#103730",
    buttonMediaFontColor: "#ffc2c2ed",
    landingPageBackgroundColor: "#ffc2c2ed",
    landingPageFontColor: "#103730",
    contactPageBackgroundColor: "#103730",
    contactPageFontColor: "#ffc2c2ed",
    salonPageBackgroundColor: "#103730",
    salonPageFontColor: "#ffc2c2ed",
    loginPageBackgroundColor: "#103730",
    loginPageFontColor: "#ffc2c2ed",
    signupPageBackgroundColor: "#103730",
    signupPageFontColor: "#ffc2c2ed",
    stylistPageBackgroundColor: "#103730",
    stylistPageFontColor: "#ffc2c2ed",
    bg: "#faeec8c9",
    color: "#91a681b8",
    secondaryColor: "#8fC1E3",
    tirtiaryColor: "#F7F9FB",
    backgroundColor: "linear-gradient(to right, #fadaddc4,#91a681)",
    modalBackgroundColor: "linear-gradient(to right, #894545c5,#384126d0)",
    screenSize,
    sectionSizes,
  },
}
// Forest Green
// Pale Pink
// Champagne Gold
const themeNanah4 = {
  baseTheme: {
    id: "baseTheme",
    headerBackgroundColor: "#fae1e4d4",
    headerFontColor: "#103730",
    menuBackgroundColor: "#fae1e4d4",
    menuFontColor: "#103730",
    heroBackgroundColor: "#fae1e4d4",
    heroFontColor: "#103730",
    mainBackgroundColor: "#fae1e4d4",
    mainFontColor: "#103730",
    footerBackgroundColor: "#fae1e4d4",
    footerFontColor: "#103730",
    modalBackdropBackgroundColor: "#fae1e4d4",
    modalBackdropFontColor: "#103730",
    modalOverlayBackgroundColor: "#fae1e4d4",
    modalOverlayFontColor: "#103730",
    toggleBackgroundColor: "#103730",
    toggleFontColor: "#103730",
    rightBackgroundColor: "#fae1e4d4",
    rightFontColor: "#103730",
    accentBackgroundColor: "#103730",
    accentFontColor: "#103730",
    socialMediaBackgroundColor: "#fae1e4d4",
    socialMediaFontColor: "#103730",
    buttonMediaBackgroundColor: "#fae1e4d4",
    buttonMediaFontColor: "#103730",
    landingPageBackgroundColor: "#103730",
    landingPageFontColor: "#fae1e4d4",
    contactPageBackgroundColor: "#fae1e4d4",
    contactPageFontColor: "#103730",
    salonPageBackgroundColor: "#fae1e4d4",
    salonPageFontColor: "#103730",
    signinPageBackgroundColor: "#fae1e4d4",
    signinPageFontColor: "#103730",
    signupPageBackgroundColor: "#fae1e4d4",
    signupPageFontColor: "#103730",
    stylistPageBackgroundColor: "#fae1e4d4",
    stylistPageFontColor: "#103730",
    bg: "#faeec8c9",
    color: "#91a681b8",
    secondaryColor: "#8fC1E3",
    tirtiaryColor: "#F7F9FB",
    backgroundColor: "linear-gradient(to right, #fadaddc4,#91a681)",
    modalBackgroundColor: "linear-gradient(to right, #894545c5,#384126d0)",
    screenSize,
    sectionSizes,
  },
  darkTheme: {
    id: "darkTheme",
    headerBackgroundColor: "#103730",
    headerFontColor: "#fae1e4d4",
    menuBackgroundColor: "#103730",
    menuFontColor: "#fae1e4d4",
    heroBackgroundColor: "#103730",
    heroFontColor: "#fae1e4d4",
    mainBackgroundColor: "#103730",
    mainFontColor: "#fae1e4d4",
    footerBackgroundColor: "#103730",
    footerFontColor: "#fae1e4d4",
    modalBackdropBackgroundColor: "#103730",
    modalBackdropFontColor: "#fae1e4d4",
    modalOverlayBackgroundColor: "#103730",
    modalOverlayFontColor: "#fae1e4d4",
    toggleBackgroundColor: "#fae1e4d4",
    toggleFontColor: "#fae1e4d4",
    rightBackgroundColor: "#103730",
    rightFontColor: "#fae1e4d4",
    accentBackgroundColor: "#fae1e4d4",
    accentFontColor: "#fae1e4d4",
    socialMediaBackgroundColor: "#103730",
    socialMediaFontColor: "#fae1e4d4",
    buttonMediaBackgroundColor: "#103730",
    buttonMediaFontColor: "#fae1e4d4",
    landingPageBackgroundColor: "#fae1e4d4",
    landingPageFontColor: "#103730",
    contactPageBackgroundColor: "#103730",
    contactPageFontColor: "#fae1e4d4",
    salonPageBackgroundColor: "#103730",
    salonPageFontColor: "#fae1e4d4",
    loginPageBackgroundColor: "#103730",
    loginPageFontColor: "#fae1e4d4",
    signupPageBackgroundColor: "#103730",
    signupPageFontColor: "#fae1e4d4",
    stylistPageBackgroundColor: "#103730",
    stylistPageFontColor: "#fae1e4d4",
    bg: "#faeec8c9",
    color: "#91a681b8",
    secondaryColor: "#8fC1E3",
    tirtiaryColor: "#F7F9FB",
    backgroundColor: "linear-gradient(to right, #fadaddc4,#91a681)",
    modalBackgroundColor: "linear-gradient(to right, #894545c5,#384126d0)",
    screenSize,
    sectionSizes,
  },
}

const themeNanah3 = {
  baseTheme: {
    id: "baseTheme",
    headerBackgroundColor: "#FADADD",
    headerFontColor: "#164A41",
    menuBackgroundColor: "#FADADD",
    menuFontColor: "#164A41",
    heroBackgroundColor: "#FADADD",
    heroFontColor: "#164A41",
    mainBackgroundColor: "#FADADD",
    mainFontColor: "#164A41",
    footerBackgroundColor: "#FADADD",
    footerFontColor: "#164A41",
    modalBackdropBackgroundColor: "#FADADD",
    modalBackdropFontColor: "#164A41",
    modalOverlayBackgroundColor: "#FADADD",
    modalOverlayFontColor: "#164A41",
    toggleBackgroundColor: "#164A41",
    toggleFontColor: "#164A41",
    rightBackgroundColor: "#FADADD",
    rightFontColor: "#164A41",
    accentBackgroundColor: "#164A41",
    accentFontColor: "#164A41",
    socialMediaBackgroundColor: "#FADADD",
    socialMediaFontColor: "#164A41",
    buttonMediaBackgroundColor: "#FADADD",
    buttonMediaFontColor: "#164A41",
    landingPageBackgroundColor: "#164A41",
    landingPageFontColor: "#FADADD",
    contactPageBackgroundColor: "#FADADD",
    contactPageFontColor: "#164A41",
    salonPageBackgroundColor: "#FADADD",
    salonPageFontColor: "#164A41",
    signinPageBackgroundColor: "#FADADD",
    signinPageFontColor: "#164A41",
    signupPageBackgroundColor: "#FADADD",
    signupPageFontColor: "#164A41",
    stylistPageBackgroundColor: "#FADADD",
    stylistPageFontColor: "#164A41",
    bg: "#faeec8c9",
    color: "#91a681b8",
    secondaryColor: "#8fC1E3",
    tirtiaryColor: "#F7F9FB",
    backgroundColor: "linear-gradient(to right, #fadaddc4,#91a681)",
    modalBackgroundColor: "linear-gradient(to right, #894545c5,#384126d0)",
    screenSize,
    sectionSizes,
  },
  darkTheme: {
    id: "darkTheme",
    headerBackgroundColor: "#164A41",
    headerFontColor: "#FADADD",
    menuBackgroundColor: "#164A41",
    menuFontColor: "#FADADD",
    heroBackgroundColor: "#164A41",
    heroFontColor: "#FADADD",
    mainBackgroundColor: "#164A41",
    mainFontColor: "#FADADD",
    footerBackgroundColor: "#164A41",
    footerFontColor: "#FADADD",
    modalBackdropBackgroundColor: "#164A41",
    modalBackdropFontColor: "#FADADD",
    modalOverlayBackgroundColor: "#164A41",
    modalOverlayFontColor: "#FADADD",
    toggleBackgroundColor: "#FADADD",
    toggleFontColor: "#FADADD",
    rightBackgroundColor: "#164A41",
    rightFontColor: "#FADADD",
    accentBackgroundColor: "#FADADD",
    accentFontColor: "#FADADD",
    socialMediaBackgroundColor: "#164A41",
    socialMediaFontColor: "#FADADD",
    buttonMediaBackgroundColor: "#164A41",
    buttonMediaFontColor: "#FADADD",
    landingPageBackgroundColor: "#FADADD",
    landingPageFontColor: "#164A41",
    contactPageBackgroundColor: "#164A41",
    contactPageFontColor: "#FADADD",
    salonPageBackgroundColor: "#164A41",
    salonPageFontColor: "#FADADD",
    signinPageBackgroundColor: "#164A41",
    signinPageFontColor: "#FADADD",
    signupPageBackgroundColor: "#164A41",
    signupPageFontColor: "#FADADD",
    stylistPageBackgroundColor: "#164A41",
    stylistPageFontColor: "#FADADD",
    bg: "#faeec8c9",
    color: "#91a681b8",
    secondaryColor: "#8fC1E3",
    tirtiaryColor: "#F7F9FB",
    backgroundColor: "linear-gradient(to right, #fadaddc4,#91a681)",
    modalBackgroundColor: "linear-gradient(to right, #894545c5,#384126d0)",
    screenSize,
    sectionSizes,
  },
}

const themeNanah2 = {
  baseTheme: {
    id: "baseTheme",
    fg: "#454547",
    bg: "#562424",
    color: "#ffffffe2",
    secondaryColor: "#8fC1E3",
    tirtiaryColor: "#F7F9FB",
    backgroundColor: "linear-gradient(to right, #24562B,#F3ADB8)",
    modalBackgroundColor: "linear-gradient(to right, #894545c5,#384126d0)",
    screenSize,
    // colors,
    sectionSizes,
  },

  darkTheme: {
    id: "darkTheme",
    fg: "#385E3C",
    bg: "#F3ADB8",
    color: "#ffffffe1",
    backgroundColor: "linear-gradient(to right, #24562B,#F3ADB8)",
    modalBackgroundColor: "linear-gradient(to right, #894545c5, #384126d0)",
    screenSize,
    // colors,
    sectionSizes,
  },
}

const themeNanah = {
  baseTheme: {
    id: "baseTheme",
    fg: "#545f3d",
    bg: "#384126d0",
    color: "#ffffffe2",
    secondaryColor: "#8fC1E3",
    tirtiaryColor: "#F7F9FB",
    backgroundColor: "linear-gradient(to right, #894545c5, #fe9c9ce0)",
    modalBackgroundColor: "linear-gradient(to right, #894545c5,#384126d0)",
    screenSize,
    // colors,
    sectionSizes,
  },

  darkTheme: {
    id: "darkTheme",
    fg: "#fe9c9ce0",
    bg: "#894545c5",
    color: "#ffffffe1",
    backgroundColor: "linear-gradient(to right, #343e1fd0, #35431a)",
    modalBackgroundColor: "linear-gradient(to right, #894545c5, #384126d0)",
    screenSize,
    // colors,
    sectionSizes,
  },
}

const themeDark = {
  baseTheme: {
    id: "baseTheme",
    fg: "#89b82b",
    bg: "#83b324d0",
    color: "#ffffffe2",
    secondaryColor: "#8fC1E3",
    tirtiaryColor: "#F7F9FB",
    backgroundColor: "linear-gradient(to right, #8f4a00, #ffe13a)",
    modalBackgroundColor: "linear-gradient(to right, #ad930095,#52740d80)",
    screenSize,
    // colors,
    sectionSizes,
  },

  darkTheme: {
    id: "darkTheme",
    fg: "#ea7272",
    bg: "#f09292b4",
    color: "#ffffffe1",
    backgroundColor: "linear-gradient(to right, #8f4a00, #ffe13a)",
    modalBackgroundColor: "linear-gradient(to right, #ad930091, #f0929285)",
    screenSize,
    // colors,
    sectionSizes,
  },
}

const themeLight = {
  baseTheme: {
    id: "baseTheme",
    fg: "#89b82bc2",
    bg: "#83b324cf",
    color: "#ffffff",
    secondaryColor: "#8fc1e3e1",
    tirtiaryColor: "#F7F9FB",
    backgroundColor: "linear-gradient(to right, #8f4a00d5, #ffe13ac9)",
    modalBackgroundColor: "linear-gradient(to right, #ad930092,#52740d9b)",
    screenSize,
    // colors,
    sectionSizes,
  },

  darkTheme: {
    id: "darkTheme",
    fg: "#ea7272ca",
    bg: "#f09292d2",
    color: "#ffffff",
    backgroundColor: "linear-gradient(to right, #8f4a00d2, #ffe13acc)",
    modalBackgroundColor: "linear-gradient(to right, #ad9300bc, #f09292c7)",
    screenSize,
    // colors,
    sectionSizes,
  },
}

// This theme swaps `fg` and `bg`
const invertTheme = ({ fg, bg }) => ({
  fg: bg,
  bg: fg,
})

export default themeNanah7

// Blue

// id: "darkTheme",
// fg: "#8E8268",
// bg: "#474853",
// color: "#AAA0A0",
// backgroundColor: "linear-gradient(to right, #86B3D1, #5085A5)",

// id: "baseTheme",
// fg: "#687864",
// bg: "#31708E",
// color: "#5085A5",
// secondaryColor: "#8fC1E3",
// tirtiaryColor: "#F7F9FB",
// backgroundColor: "linear-gradient(to right, #8fC1E3, #F7F9FB)",

//Gold
// #ad9300
//Green
// #4A5D23
// pink
// #ff878d
